// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk34jl8pq4ZBuwac4jhpewcH2Ej9gd5kA',
    appId: '1:777993590363:web:6a8051b4e6851494c7117e',
    messagingSenderId: '777993590363',
    projectId: 'smartkidstracker-b3468',
    authDomain: 'smartkidstracker-b3468.firebaseapp.com',
    databaseURL: 'https://smartkidstracker-b3468-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartkidstracker-b3468.firebasestorage.app',
    measurementId: 'G-YR6WR3H57N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqbmdeyoP03vC2ql66xqPEpO9hhE3MR7Q',
    appId: '1:777993590363:android:c38f695f49d0f014c7117e',
    messagingSenderId: '777993590363',
    projectId: 'smartkidstracker-b3468',
    databaseURL: 'https://smartkidstracker-b3468-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartkidstracker-b3468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcWLBmYsjgboBNnOoh1kEJy3JUhqaEKhA',
    appId: '1:224966435149:ios:e9f5ce9c0c056d96fbd704',
    messagingSenderId: '224966435149',
    projectId: 'smartkidstracker-35ac5',
    storageBucket: 'smartkidstracker-35ac5.appspot.com',
    iosBundleId: 'com.example.smartkidstracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcWLBmYsjgboBNnOoh1kEJy3JUhqaEKhA',
    appId: '1:224966435149:ios:e9f5ce9c0c056d96fbd704',
    messagingSenderId: '224966435149',
    projectId: 'smartkidstracker-35ac5',
    storageBucket: 'smartkidstracker-35ac5.appspot.com',
    iosBundleId: 'com.example.smartkidstracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk34jl8pq4ZBuwac4jhpewcH2Ej9gd5kA',
    appId: '1:777993590363:web:cb8ce441f7a2aa96c7117e',
    messagingSenderId: '777993590363',
    projectId: 'smartkidstracker-b3468',
    authDomain: 'smartkidstracker-b3468.firebaseapp.com',
    databaseURL: 'https://smartkidstracker-b3468-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartkidstracker-b3468.firebasestorage.app',
    measurementId: 'G-BMPNY13KNV',
  );

}