// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMv1qo2yUFDipXIdQOiccpv_7vkkX0VtA',
    appId: '1:224966435149:web:dc5aee26c099bbe3fbd704',
    messagingSenderId: '224966435149',
    projectId: 'smartkidstracker-35ac5',
    authDomain: 'smartkidstracker-35ac5.firebaseapp.com',
    storageBucket: 'smartkidstracker-35ac5.appspot.com',
    measurementId: 'G-ZQTV3D0VQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoxbr2DTijagxq5Dnjb3vm6UCgP3TxTuM',
    appId: '1:224966435149:android:f9008b6f07107025fbd704',
    messagingSenderId: '224966435149',
    projectId: 'smartkidstracker-35ac5',
    storageBucket: 'smartkidstracker-35ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcWLBmYsjgboBNnOoh1kEJy3JUhqaEKhA',
    appId: '1:224966435149:ios:e9f5ce9c0c056d96fbd704',
    messagingSenderId: '224966435149',
    projectId: 'smartkidstracker-35ac5',
    storageBucket: 'smartkidstracker-35ac5.appspot.com',
    iosBundleId: 'com.example.smartkidstracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcWLBmYsjgboBNnOoh1kEJy3JUhqaEKhA',
    appId: '1:224966435149:ios:e9f5ce9c0c056d96fbd704',
    messagingSenderId: '224966435149',
    projectId: 'smartkidstracker-35ac5',
    storageBucket: 'smartkidstracker-35ac5.appspot.com',
    iosBundleId: 'com.example.smartkidstracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMv1qo2yUFDipXIdQOiccpv_7vkkX0VtA',
    appId: '1:224966435149:web:5596b090b687b0abfbd704',
    messagingSenderId: '224966435149',
    projectId: 'smartkidstracker-35ac5',
    authDomain: 'smartkidstracker-35ac5.firebaseapp.com',
    storageBucket: 'smartkidstracker-35ac5.appspot.com',
    measurementId: 'G-8Z81JFBH8W',
  );
}
